
### model
model_name_or_path: /data2/lyh/base_model/Qwen2.5-Coder-7B
trust_remote_code: true

### method
stage: pt
do_train: true
finetuning_type: lora
lora_rank: 256
lora_alpha: 512
lora_target: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: ArktsL2RTrain20M
template: plain
cutoff_len: 2048
# max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /data2/lyh/output_models/qwen_7b_lora256_pretrain20M_2klen_32Seq
logging_steps: 5
plot_loss: true
save_steps: 500
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 1e-4
num_train_epochs: 1.5
lr_scheduler_type: cosine
warmup_ratio: 0.02
bf16: true
weight_decay: 0.01
ddp_timeout: 180000000
resume_from_checkpoint: null
seed: 42

### eval
eval_dataset: ArktsVal, TypeScriptVal
eval_on_each_dataset: true
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 40