
### model
model_name_or_path: /data2/lyh/output_models/qwen_7b_full_pretrain_50k_68k_mix_5e-5
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 256
lora_alpha: 256
lora_target: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
deepspeed: examples/deepspeed/ds_z3_config.json
log_sample_order: false

### dataset
dataset: DZ_203_SFT, ZetaTrainSFT
template: plain
cutoff_len: 2048
# max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /data2/lyh/output_models/qwen_7b_full_pretrain_50k_68k_mix_zeta_dz_sft_5e-5
logging_steps: 5
plot_loss: true
save_steps: 500
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard

### train on 1 npu
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 2.0e-4
max_steps: 90
lr_scheduler_type: linear
weight_decay: 0.01
# optim: adamw_torch
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
seed: 42

### eval
eval_dataset: ZetaEvalSFT, TEST_SFT_0825_LINE
eval_on_each_dataset: true
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 10